NumPy is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.
 Many advanced data science and machine learning libraries require data to be in the form of NumPy arrays before it can be processed.


## Advantages of NumPy Library
1. NumPy arrays are much faster for insertion, deletion, updating, and reading of data.
2. NumPy arrays contain advanced broadcasting functionalities compared with regular Python arrays.
3. NumPy array comes with a lot of methods that support advanced arithmetic and linear algebra options.
4. NumPy provides advanced multi-dimensional array slicing capabilities.


The Numpy module is mainly used for working with numerical  data. It provides us with a powerful object known as an Array.

With Arrays, we can perform mathematical operations on  multiple values in the Arrays at the same time, and also perform operations between different Arrays, similar to  matrix operations. 


## NumPy Arrays
NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).


In [3]:
import numpy as np

In [4]:
np.__version__

'1.16.5'

In [5]:
nums_list = [10, 12, 14, 16, 18, 20]
type(nums_list)

list

To create a NumPy array, you can pass a list to the array() method of the NumPy module as shown below:

In [7]:
nums_array = np.array(nums_list)
print(nums_array)
type(nums_array)

[10 12 14 16 18 20]


numpy.ndarray

You can also create a multi-dimensional NumPy array. To do so, you need to create a list of lists where each internal list corresponds to the row in a 2-dimensional array. Here is an example of how to create a 2-dimensional array using the array() method.

In [9]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
print(my_matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [13]:
num_2d = np.array(my_matrix)
num_2d.shape

(3, 3)

## Built-in Methods

### arange


With the arrange () method, you can create a NumPy array that contains a range of integers. The first parameter to the arrange method is the lower bound, and the second parameter is the upper bound. The lower bound is included in the array. However, the upper bound is not included.

In [18]:
nums_arr = np.arange(1,11)
nums_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
nums_arr1 = np.arange(1,11,3)
nums_arr1

array([ 1,  4,  7, 10])

### zeros
The zeros() method can be used to create a NumPy array of all zeros. Here is an example.

In [19]:
np.zeros(3)

array([0., 0., 0.])

In [21]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### ones
The ones() method can be used to create a NumPy array of all ones. Here is an example.

In [22]:
np.ones(4)

array([1., 1., 1., 1.])

In [23]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### eye 
The eye() method is used to create an identity matrix in the form of a 2-dimensional numPy array. An identity contains 1s along the diagonal, while the rest of the elements are 0 in the array.

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [28]:
np.linspace(1, 10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [27]:
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## Random
### rand
The random.rand() function from the NumPy module can be used to create a NumPy array with uniform distribution.

In [29]:
np.random.rand(5)

array([0.3635286 , 0.58464826, 0.61589437, 0.90299445, 0.69755749])

In [30]:
np.random.rand(4, 5)

array([[0.22318193, 0.7874424 , 0.50959781, 0.38906194, 0.84324507],
       [0.06066906, 0.77238474, 0.71199686, 0.99765794, 0.33631842],
       [0.44265739, 0.15324285, 0.2638679 , 0.45265152, 0.72329378],
       [0.83324998, 0.50342715, 0.96653717, 0.55798123, 0.22335588]])

### randn
The random.randn() function from the NumPy module can be used to create a NumPy array with normal distribution, as shown in the following example.

In [31]:
np.random.randn(5)

array([-0.65210549, -0.72753453, -0.7443014 , -0.09995791, -0.24866629])

In [32]:
np.random.randn(4,4)

array([[-0.82907104, -1.24192063, -0.50768878,  0.04913398],
       [ 0.06527274, -0.54426489, -0.66811938,  0.27878827],
       [-0.10015733, -0.27960589,  0.868985  , -0.14309906],
       [-0.98942721, -0.46538922,  0.20538907, -0.83559084]])

### randint
Finally, the random.randint() function from the NumPy module can be used to create a NumPy array with random integers between a certain range. The first parameter to the randint() function specifies the lower bound, the second parameter specifies the upper bound, while the last parameter specifies the number of random integers to generate between the range.

In [34]:
np.random.randint(1,50)

35

In [36]:
np.random.randint(1,50,9)

array([ 7,  2, 12, 17,  3, 27, 24, 36, 26])

### reshape
Returns an array containing the same data with a new shape.

In [38]:
arr1 = np.random.randint(1,50,9)
arr1.reshape(3,3)

array([[15, 34, 43],
       [ 7, 46, 45],
       [43,  4,  9]])

In [39]:
arr1.reshape(9,1)

array([[15],
       [34],
       [43],
       [ 7],
       [46],
       [45],
       [43],
       [ 4],
       [ 9]])

### max, min, argmax, argmin
These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [40]:
arr1

array([15, 34, 43,  7, 46, 45, 43,  4,  9])

In [41]:
arr1.max()

46

In [42]:
arr1.min() # minimum value in the array

4

In [43]:
arr1.argmax() # Position of the maximum value

4

In [44]:
arr1.argmin()

7

## Array Indexing and Slicing
NumPy arrays can be indexed and sliced. Slicing an array means dividing an array into multiple parts.
NumPy arrays are indexed just like normal lists. Indexes in NumPy arrays start from 0, which means that the first item of a NumPy array is stored at the 0th index.

In [46]:
arr2 = np.arange(1,11)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr2[6]

7

In [49]:
arr2[2:7]

array([3, 4, 5, 6, 7])

In [52]:
arr2[0:5]=100
arr2

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [60]:
arr3 = np.arange(1,11)
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
slice_of_arr3 = arr3[5:10]
slice_of_arr3

array([ 6,  7,  8,  9, 10])

In [63]:
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
slice_of_arr3[:]=99
slice_of_arr3

array([99, 99, 99, 99, 99])

In [65]:
arr3

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99])

In [66]:
arr4 = np.arange(1,11)
arr4_copy = arr4.copy()

arr4_copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
arr4_copy[:]=56
arr4_copy

array([56, 56, 56, 56, 56, 56, 56, 56, 56, 56])

In [68]:
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Indexing a 2D array
Array slicing can also be applied on a 2-dimensional array. To do so, you have to apply slicing on arrays and columns separately. A comma separates the rows and columns slicing. 

In [69]:
arr1_2d = np.array(([5,10,15],[20,25,30],[30,35,40]))
arr1_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [30, 35, 40]])

In [70]:
arr1_2d[0]

array([ 5, 10, 15])

In [71]:
arr1_2d[1][2]

30

In [72]:
arr1_2d[1,2]

30

In [73]:
arr1_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [74]:
arr1_2d[:2,:2]

array([[ 5, 10],
       [20, 25]])

### Selection
Let's briefly go over how to use brackets for selection based off of comparison operators

In [2]:
import numpy as np

In [3]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [5]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [6]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [7]:
x = 6
arr[arr>x]

array([ 7,  8,  9, 10])

## Arithmetic Operations
NumPy arrays provide a variety of functions to perform arithmetic operations. Some of these functions are explained in this section.

In [10]:
arr
arr1 = np.random.randint(1,30,10)
arr1

array([25, 13, 14, 28, 10, 10, 24,  3,  2, 21])

In [12]:
arr + 10

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [13]:
arr + arr1

array([26, 15, 17, 32, 15, 16, 31, 11, 11, 31])

In [15]:
arr * arr1

array([ 25,  26,  42, 112,  50,  60, 168,  24,  18, 210])

In [16]:
arr1 / arr

array([25.        ,  6.5       ,  4.66666667,  7.        ,  2.        ,
        1.66666667,  3.42857143,  0.375     ,  0.22222222,  2.1       ])

In [17]:
arr1**3

array([15625,  2197,  2744, 21952,  1000,  1000, 13824,    27,     8,
        9261], dtype=int32)

In [18]:
np.array([4, 67, 34, 67])/np.array([0, 5, 7, 4])

C:\Users\UZOMA\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf, 13.4       ,  4.85714286, 16.75      ])

In [19]:
np.sqrt(arr1)

array([5.        , 3.60555128, 3.74165739, 5.29150262, 3.16227766,
       3.16227766, 4.89897949, 1.73205081, 1.41421356, 4.58257569])

In [20]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [5]:
a =[3, 7]
b = a

In [6]:
b

[3, 7]

In [7]:
b = [5, 8]

In [8]:
a

[3, 7]